services:
  _defaults:
    autowire: true
    autoconfigure: true

  # DataFixtures services for development environment
  Tourze\IdleLockScreenBundle\DataFixtures\:
    resource: '../../DataFixtures/*'
    tags: ['doctrine.fixture.orm']