services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Tourze\IdleLockScreenBundle\Controller\:
    resource: '../../Controller/'
  Tourze\IdleLockScreenBundle\EventListener\:
    resource: '../../EventListener/'
  Tourze\IdleLockScreenBundle\Repository\:
    resource: '../../Repository/'
  Tourze\IdleLockScreenBundle\Service\:
    resource: '../../Service/'
  Tourze\IdleLockScreenBundle\Twig\:
    resource: '../../Twig/'
